site_name: My Thoughts

# Naviation
nav:
  - Home: index.md
  - About: about.md
  - Ethical Theory:
    - Original/Ethics/Literature Overview.md
    - My Position: 
      - Original/Ethics/My Position/Normativity.md
      - Original/Ethics/My Position/Normative Psychology.md
      - Original/Ethics/My Position/Normative Correctness.md
      - Original/Ethics/My Position/Moral Psychology.md
      - Original/Ethics/My Position/Moral Reasons.md
      - Original/Ethics/My Position/My Substantive Morality.md
    - Criticisms:
      - Original/Ethics/Criticisms/Naturalism.md
      - Original/Ethics/Criticisms/Non-naturalism.md
      - Original/Ethics/Criticisms/Descriptivism.md 
  - Applied Ethics:
    - Original/Other/Abortion.md
    - Original/Other/Affirmative Action In Universities.md
    - Original/Other/Against Libertarianism.md
    - Original/Other/Objective Morality.md
  - Other Philosophy:
    - Original/Other/Free Will.md
    - Original/Other/Against Presuppositionalism.md
    - Original/Other/Cosmological Argument For God.md
    - Original/Other/Destiny.md
    - Original/Other/The Problem of Evil.md
  - Random Reddit Posts:
    - Original/Other/Equality.md
    - Original/Other/Race and IQ.md
  - Other:
    - Original/Other/Taxonomy of Propositions.md
  - Summaries:
    - Non-Descriptivism:
      - Summaries/Non-descriptivism/A.J. Ayer, Critique of Ethics.md
      - Summaries/Non-descriptivism/Allan Gibbard, Wise Choices Apt Feelings.md
      - Simon Blackburn, How to be an Ethical Antirealist: index.md 
    - Motives, Reasons and Morality:
      - Summaries/Motives, Reasons and Morality/Bernard Williams, Internal and External Reasons.md
      - Summaries/Motives, Reasons and Morality/Philippa Foot, Morality as a System of Hypothetical Imperatives.md
    - Error Theory:
      - "Summaries/Error Theory/J.L. Mackie, From Ethics: Inventing Right and Wrong.md"
    - Naturalism:
      - Summaries/Naturalism/Peter Railton, Moral Realism.md
      - Michael Smith, The Moral Problem.md:
        - Summaries/Naturalism/Michael Smith, The Moral Problem/1 - Introduction.md
        - Summaries/Naturalism/Michael Smith, The Moral Problem/2 - The Expressivist Challenge.md
        - Summaries/Naturalism/Michael Smith, The Moral Problem/3 - The Externalist Challenge.md
        - Summaries/Naturalism/Michael Smith, The Moral Problem/4 - Humean Theory of Motivation.md
        - Summaries/Naturalism/Michael Smith, The Moral Problem/5 - Anti-Humean Theory of Normative Reasons.md
        - Summaries/Naturalism/Michael Smith, The Moral Problem/6 - Solution to the Moral Problem.md
    - Non-Naturalism:
      - Summaries/Non-naturalism/G.E. Moore, from Principia Ethica.md 
    - Sensibility Theory:
      - John McDowell, Values and Secondary Qualities: index.md
      - David Wiggins, A Sensible Subjectivism: index.md
    - Constructivism:
      - Summaries/Constructivism/Aaron James, Constructing Protagorean Objectivity.md
      - Summaries/Constructivism/Christine Korsgaard, The Sources of Normativity.md
      - Summaries/Constructivism/Jay Wallace, Constructivism About Normativity.md
      - Summaries/Constructivism/Sharon Street, Coming to Terms with Contingency.md
      - Summaries/Constructivism/Sharon Street, Constructivism about Reasons.md
      - Summaries/Constructivism/Sharon Street, What is Constructivism in Ethics and Metaethics.md
      - Thomas Scanlon, What We Owe to Each Other:
        - Summaries/Constructivism/Thomas Scanlon, What we Owe to Each Other/1 - Reasons.md
        - Summaries/Constructivism/Thomas Scanlon, What we Owe to Each Other/2 - Values.md
        - Summaries/Constructivism/Thomas Scanlon, What we Owe to Each Other/3 - Well-being.md
        - Summaries/Constructivism/Thomas Scanlon, What we Owe to Each Other/4 - Wrongness and Reasons.md 
        - Summaries/Constructivism/Thomas Scanlon, What we Owe to Each Other/5 - The Structure of Contractualism.md

# Theme configuration
theme: 
  name: null
  custom_dir: '/Users/jaymoss520/Personal/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'cloud'
  feature:
    tabs: false

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.details

extra_css: [extra.css]