site_name: My Thoughts

# Naviation
nav:
  - Home: index.md
  - About: about.md
  - Original:
    - Metaethics:
      - Original/Metaethics/Literature Overview.md
      - Objections:
        - Original/Metaethics/Naturalism.md
        - Original/Metaethics/Non-naturalism.md
        - Original/Metaethics/Descriptivism.md
        - Original/Metaethics/Non-descriptivism.md
      - My Position:
        - Original/Metaethics/Normativity.md
        - Original/Metaethics/Rational Psychology.md
        - Original/Metaethics/Rational Correctness.md
        - Original/Metaethics/Moral Psychology.md
        - Original/Metaethics/Moral Correctness.md
    - Ethical Theory: 
      - My Position: Original/Metaethics/My Substantive Morality.md
    - Applied Ethics:
      - Original/Other/Abortion.md
      - Original/Other/Affirmative Action In Universities.md
      - Original/Other/Against Libertarianism.md
      - Original/Other/Objective Morality.md
    - Other Philosophy:
      - Compatibilism: Original/Other/Free Will.md
      - Original/Other/Against Presuppositionalism.md
      - Original/Other/Cosmological Argument For God.md
      - Original/Other/Destiny.md
      - Original/Other/The Problem of Evil.md
    - Random Reddit Posts:
      - Original/Other/Equality.md
      - Original/Other/Race and IQ.md
    - Other:
      - Original/Other/Taxonomy of Propositions.md
  - Summaries:
    - Completed:
      - Summaries/G.E. Moore, from Principia Ethica.md
      - Summaries/A.J. Ayer, Critique of Ethics.md
      - "Summaries/J.L. Mackie, From Ethics: Inventing Right and Wrong.md"
      - Summaries/Allan Gibbard, Wise Choices Apt Feelings.md
      - Summaries/Michael Smith, The Moral Problem.md
      - Summaries/Sharon Street, Constructivism about Reasons.md
      - Summaries/Sharon Street, What is Constructivism in Ethics and Metaethics.md
    - In Progress:
      - Summaries/Bernard Williams, Internal and External Reasons.md
      - Summaries/Philippa Foot, Morality as a System of Hypothetical Imperatives.md
      - Summaries/Peter Railton, Moral Realism.md
      - Summaries/Christine Korsgaard, The Sources of Normativity.md
      - Simon Blackburn, How to be an Ethical Antirealist: index.md 
      - John McDowell, Values and Secondary Qualities: index.md
      - David Wiggins, A Sensible Subjectivism: index.md
      - Thomas Scanlon, What we owe to each other: index.md

  - Outlines:
      - Outlines/Libertarianism.md
      - Outlines/Political.md 

# Theme configuration
theme: 
  name: null
  custom_dir: '/Users/jaymoss520/Private/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'cloud'
  feature:
    tabs: false

markdown_extensions:
  - markdown_include.include:
      base_path: docs

extra_css: [extra.css]